name: Daily Fire Map Update

on:
  schedule:
    # Runs at 8 AM PST every day
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allow for manual triggering from GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to have access to your scripts
    - name: Checkout repository
      uses: actions/checkout@v3 

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3 
      with:
        python-version: '3.x'

    # Install dependencies and run each step
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run extract script
      run: |
        python scripts/extract.py

    - name: Run transform script
      run: |
        python scripts/transform.py

    - name: Run visualize script
      run: |
        python scripts/load.py

    # Upload the updated map to S3 bucket
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp fire_interactive_map.html s3://viirs-active-fire-map/fire_interactive_map.html --region us-west-1